//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_ACTUATOR_H
#define RIAPS_CORE_ACTUATOR_H

#include "componentmodel/r_componentbase.h"
#include "ForceType.capnp.h"

// Name of the ports from the model file
#define PORT_SUB_FORCE "force"

namespace sltest {
   namespace components {
      
      class ActuatorBase : public riaps::ComponentBase {
         
         public:
         ActuatorBase(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnForce (const ForceType::Reader &message,
         riaps::ports::PortBase *port)=0;
         
         virtual ~ActuatorBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_ACTUATOR_H
