//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_CONTROLLERSL_H
#define RIAPS_CORE_CONTROLLERSL_H

#include "componentmodel/r_componentbase.h"
#include "ForceType.capnp.h"
#include "PositionType.capnp.h"

// Name of the ports from the model file
#define PORT_PUB_FORCE "force"
#define PORT_SUB_POSITION "position"

namespace sltest {
   namespace components {
      
      class ControllerSLBase : public riaps::ComponentBase {
         
         public:
         ControllerSLBase(_component_conf &config, riaps::Actor &actor);
         
         virtual bool SendForce(capnp::MallocMessageBuilder& messageBuilder,
         ForceType::Builder& message);
         
         virtual void OnPosition (const PositionType::Reader &message,
         riaps::ports::PortBase *port)=0;
         
         virtual ~ControllerSLBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_CONTROLLERSL_H
