//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_SENSOR_H
#define RIAPS_CORE_SENSOR_H

#include "componentmodel/r_componentbase.h"
#include "PositionType.capnp.h"

// Name of the ports from the model file
#define PORT_TIMER_CLOCK "clock"
#define PORT_PUB_POSITION "position"

namespace sltest {
   namespace components {
      
      class SensorBase : public riaps::ComponentBase {
         
         public:
         SensorBase(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnClock(riaps::ports::PortBase *port)=0;
         
         virtual bool SendPosition(capnp::MallocMessageBuilder& messageBuilder,
         PositionType::Builder& message);
         
         virtual ~SensorBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_SENSOR_H
